import './globals.css'
import Header from "@/app/components/Header";
import { Mulish } from 'next/font/google'

const mulish = Mulish({
  weight: ['300','400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Netflix India – Watch TV Shows Online, Watch Movies Online',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
        <head>
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body>
      <Header/>
        {children}
      </body>
    </html>
  )
}
